services:
  elasticsearch-search:
    image: docker.io/elastic/elasticsearch:8.15.0
    container_name: elasticsearch-search
    ports:
      - "9201:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      node.name: "search-node"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: false
    networks:
      - elk

  kibana-search:
    image: docker.io/elastic/kibana:8.15.0
    container_name: kibana-search
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch-search:9200"
      xpack.security.enabled: "false"
    ports:
      - "5602:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch-search

  db:
    image: postgres:16-alpine
    container_name: profinder-db
    environment:
      POSTGRES_DB: profinder_db
      POSTGRES_USER: iarylser
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - elk

  minio:
    image: quay.io/minio/minio:latest
    container_name: profinder-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: iarylser
      MINIO_ROOT_PASSWORD: 1234567890
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - elk

  redis:
    image: redis:3.2
    container_name: profinder-redis
    ports:
      - "6379:6379"
    networks:
      - elk

volumes:
  db_data:
  minio_data:

networks:
  elk:
    driver: bridge
