version: '3.2'

services:
  elasticsearch:
    image: docker.io/elastic/elasticsearch:8.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: false
    networks:
      - elk

  logstash:
    image: docker.io/elastic/logstash:8.15.0
    volumes:
      - ./src/main/resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
      - "4560:4560"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.io/elastic/kibana:8.15.0
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      xpack.security.enabled: "false"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  db:
    image: postgres:16-alpine
    container_name: profinder-db
    environment:
      POSTGRES_DB: profinder_db
      POSTGRES_USER: iarylser
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - elk

volumes:
  db_data:

networks:
  elk:
    driver: bridge