version: '3.2'

services:
  elasticsearch-logs:
    image: docker.io/elastic/elasticsearch:8.15.0
    container_name: elasticsearch-logs
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: false
    networks:
      - elk

  elasticsearch-search:
    image: docker.io/elastic/elasticsearch:8.15.0
    container_name: elasticsearch-search
    ports:
      - "9201:9200"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      node.name: "search-node"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      cluster.routing.allocation.disk.threshold_enabled: false
    networks:
      - elk

  logstash:
    image: docker.io/elastic/logstash:8.15.0
    volumes:
      - ./src/main/resources/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "12201:12201/udp"
      - "5000:5000"
      - "9600:9600"
      - "4560:4560"
    networks:
      - elk
    depends_on:
      - elasticsearch-logs

  kibana-logs:
    image: docker.io/elastic/kibana:8.15.0
    container_name: kibana-logs
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch-logs:9200"
      xpack.security.enabled: "false"
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch-logs

  kibana-search:
    image: docker.io/elastic/kibana:8.15.0
    container_name: kibana-search
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch-search:9200"
      xpack.security.enabled: "false"
    ports:
      - "5602:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch-search

  db:
    image: postgres:16-alpine
    container_name: profinder-db
    environment:
      POSTGRES_DB: profinder_db
      POSTGRES_USER: iarylser
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - elk

  minio:
    image: quay.io/minio/minio:latest
    container_name: profinder-minio
    ports:
      - "9000:9000"  # API (S3)
      - "9001:9001"  # Web UI
    environment:
      MINIO_ROOT_USER: iarylser
      MINIO_ROOT_PASSWORD: 1234567890
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - elk


volumes:
  db_data:
  minio_data:

networks:
  elk:
    driver: bridge
